<?php
/**
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by install script
 * Date: Mon, 25 May 2015 16:05:47 +0000
 */
$conf['title'] = 'wiki';
$conf['lang'] = 'en';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 0;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
