<?php
/*
 * Local plugin enable/disable settings
 *
 * Auto-generated by install script
 * Date: Mon, 25 May 2015 16:05:47 +0000
 */

$plugins['authad']    = 0;
$plugins['authldap']  = 0;
$plugins['authmysql'] = 0;
$plugins['authpgsql'] = 0;
